# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total.ui'
#
# Created: Fri Jun 05 22:46:48 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_total(object):
    def setupUi(self, total):
        total.setObjectName(_fromUtf8("total"))
        total.setEnabled(True)
        total.resize(1000, 600)
        self.centralWidget = QtGui.QWidget(total)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(470, 0, 531, 276))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layout_pipeline = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_pipeline.setContentsMargins(5, 0, 5, 0)
        self.layout_pipeline.setObjectName(_fromUtf8("layout_pipeline"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_write_back = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_write_back.setObjectName(_fromUtf8("label_write_back"))
        self.horizontalLayout_11.addWidget(self.label_write_back)
        self.text_D_icode_5 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode_5.sizePolicy().hasHeightForWidth())
        self.text_D_icode_5.setSizePolicy(sizePolicy)
        self.text_D_icode_5.setObjectName(_fromUtf8("text_D_icode_5"))
        self.horizontalLayout_11.addWidget(self.text_D_icode_5)
        self.text_D_icode_4 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode_4.sizePolicy().hasHeightForWidth())
        self.text_D_icode_4.setSizePolicy(sizePolicy)
        self.text_D_icode_4.setObjectName(_fromUtf8("text_D_icode_4"))
        self.horizontalLayout_11.addWidget(self.text_D_icode_4)
        self.text_D_icode_3 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode_3.sizePolicy().hasHeightForWidth())
        self.text_D_icode_3.setSizePolicy(sizePolicy)
        self.text_D_icode_3.setObjectName(_fromUtf8("text_D_icode_3"))
        self.horizontalLayout_11.addWidget(self.text_D_icode_3)
        self.text_D_icode_2 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode_2.sizePolicy().hasHeightForWidth())
        self.text_D_icode_2.setSizePolicy(sizePolicy)
        self.text_D_icode_2.setObjectName(_fromUtf8("text_D_icode_2"))
        self.horizontalLayout_11.addWidget(self.text_D_icode_2)
        self.text_D_icode_6 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode_6.sizePolicy().hasHeightForWidth())
        self.text_D_icode_6.setSizePolicy(sizePolicy)
        self.text_D_icode_6.setObjectName(_fromUtf8("text_D_icode_6"))
        self.horizontalLayout_11.addWidget(self.text_D_icode_6)
        self.layout_pipeline.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_memory = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_memory.setObjectName(_fromUtf8("label_memory"))
        self.horizontalLayout_12.addWidget(self.label_memory)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_12.addWidget(self.label_20)
        self.layout_pipeline.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_execute = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_execute.setObjectName(_fromUtf8("label_execute"))
        self.horizontalLayout_13.addWidget(self.label_execute)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_13.addWidget(self.label_22)
        self.layout_pipeline.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_decode = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_decode.sizePolicy().hasHeightForWidth())
        self.label_decode.setSizePolicy(sizePolicy)
        self.label_decode.setObjectName(_fromUtf8("label_decode"))
        self.horizontalLayout_14.addWidget(self.label_decode)
        self.text_D_icode = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_icode.sizePolicy().hasHeightForWidth())
        self.text_D_icode.setSizePolicy(sizePolicy)
        self.text_D_icode.setObjectName(_fromUtf8("text_D_icode"))
        self.horizontalLayout_14.addWidget(self.text_D_icode)
        self.text_D_ifun = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_D_ifun.sizePolicy().hasHeightForWidth())
        self.text_D_ifun.setSizePolicy(sizePolicy)
        self.text_D_ifun.setObjectName(_fromUtf8("text_D_ifun"))
        self.horizontalLayout_14.addWidget(self.text_D_ifun)
        self.textBrowser_6 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.horizontalLayout_14.addWidget(self.textBrowser_6)
        self.textBrowser_5 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.horizontalLayout_14.addWidget(self.textBrowser_5)
        self.textBrowser_4 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.horizontalLayout_14.addWidget(self.textBrowser_4)
        self.textBrowser_3 = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.horizontalLayout_14.addWidget(self.textBrowser_3)
        self.layout_pipeline.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_fetch = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fetch.sizePolicy().hasHeightForWidth())
        self.label_fetch.setSizePolicy(sizePolicy)
        self.label_fetch.setObjectName(_fromUtf8("label_fetch"))
        self.horizontalLayout_15.addWidget(self.label_fetch)
        spacerItem = QtGui.QSpacerItem(213, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.text_F_predPC = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_F_predPC.sizePolicy().hasHeightForWidth())
        self.text_F_predPC.setSizePolicy(sizePolicy)
        self.text_F_predPC.setObjectName(_fromUtf8("text_F_predPC"))
        self.horizontalLayout_15.addWidget(self.text_F_predPC)
        spacerItem1 = QtGui.QSpacerItem(160, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.layout_pipeline.addLayout(self.horizontalLayout_15)
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(620, 290, 381, 151))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 270, 171, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.table_register = QtGui.QTableWidget(self.groupBox)
        self.table_register.setGeometry(QtCore.QRect(10, 20, 144, 227))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_register.sizePolicy().hasHeightForWidth())
        self.table_register.setSizePolicy(sizePolicy)
        self.table_register.setShowGrid(True)
        self.table_register.setWordWrap(True)
        self.table_register.setCornerButtonEnabled(True)
        self.table_register.setRowCount(8)
        self.table_register.setObjectName(_fromUtf8("table_register"))
        self.table_register.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(1, item)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(90, 10, 201, 191))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(70, 210, 241, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 270, 160, 251))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.button_continue = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_continue.sizePolicy().hasHeightForWidth())
        self.button_continue.setSizePolicy(sizePolicy)
        self.button_continue.setObjectName(_fromUtf8("button_continue"))
        self.verticalLayout_3.addWidget(self.button_continue)
        self.button_pause = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setObjectName(_fromUtf8("button_pause"))
        self.verticalLayout_3.addWidget(self.button_pause)
        self.button_stop = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop.sizePolicy().hasHeightForWidth())
        self.button_stop.setSizePolicy(sizePolicy)
        self.button_stop.setObjectName(_fromUtf8("button_stop"))
        self.verticalLayout_3.addWidget(self.button_stop)
        self.button_step = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_step.sizePolicy().hasHeightForWidth())
        self.button_step.setSizePolicy(sizePolicy)
        self.button_step.setObjectName(_fromUtf8("button_step"))
        self.verticalLayout_3.addWidget(self.button_step)
        self.button_reset = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setObjectName(_fromUtf8("button_reset"))
        self.verticalLayout_3.addWidget(self.button_reset)
        total.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(total)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMain = QtGui.QMenu(self.menuBar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuTool = QtGui.QMenu(self.menuBar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        total.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(total)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        total.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(total)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        total.setStatusBar(self.statusBar)
        self.actionSo = QtGui.QAction(total)
        self.actionSo.setObjectName(_fromUtf8("actionSo"))
        self.action_run_direct = QtGui.QAction(total)
        self.action_run_direct.setObjectName(_fromUtf8("action_run_direct"))
        self.action1_IPS = QtGui.QAction(total)
        self.action1_IPS.setObjectName(_fromUtf8("action1_IPS"))
        self.action2_IPS = QtGui.QAction(total)
        self.action2_IPS.setObjectName(_fromUtf8("action2_IPS"))
        self.action3 = QtGui.QAction(total)
        self.action3.setObjectName(_fromUtf8("action3"))
        self.action_1_IPS = QtGui.QAction(total)
        self.action_1_IPS.setObjectName(_fromUtf8("action_1_IPS"))
        self.action_2_IPS = QtGui.QAction(total)
        self.action_2_IPS.setObjectName(_fromUtf8("action_2_IPS"))
        self.action_4_IPS = QtGui.QAction(total)
        self.action_4_IPS.setObjectName(_fromUtf8("action_4_IPS"))
        self.action_8_IPS = QtGui.QAction(total)
        self.action_8_IPS.setObjectName(_fromUtf8("action_8_IPS"))
        self.action_step = QtGui.QAction(total)
        self.action_step.setObjectName(_fromUtf8("action_step"))
        self.action_hex2dex = QtGui.QAction(total)
        self.action_hex2dex.setObjectName(_fromUtf8("action_hex2dex"))
        self.action_dec2hex = QtGui.QAction(total)
        self.action_dec2hex.setObjectName(_fromUtf8("action_dec2hex"))
        self.action_7 = QtGui.QAction(total)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_load_file = QtGui.QAction(total)
        self.action_load_file.setVisible(True)
        self.action_load_file.setObjectName(_fromUtf8("action_load_file"))
        self.action_save_process = QtGui.QAction(total)
        self.action_save_process.setObjectName(_fromUtf8("action_save_process"))
        self.action_load_process = QtGui.QAction(total)
        self.action_load_process.setObjectName(_fromUtf8("action_load_process"))
        self.actionAbout = QtGui.QAction(total)
        self.actionAbout.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        self.actionAbout.setFont(font)
        self.actionAbout.setIconVisibleInMenu(False)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_14 = QtGui.QAction(total)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_read_memory = QtGui.QAction(total)
        self.action_read_memory.setObjectName(_fromUtf8("action_read_memory"))
        self.action_write_memory = QtGui.QAction(total)
        self.action_write_memory.setObjectName(_fromUtf8("action_write_memory"))
        self.action_total = QtGui.QAction(total)
        self.action_total.setObjectName(_fromUtf8("action_total"))
        self.action_pipeline = QtGui.QAction(total)
        self.action_pipeline.setObjectName(_fromUtf8("action_pipeline"))
        self.action_instruction = QtGui.QAction(total)
        self.action_instruction.setObjectName(_fromUtf8("action_instruction"))
        self.action_pause = QtGui.QAction(total)
        self.action_pause.setObjectName(_fromUtf8("action_pause"))
        self.action_stop = QtGui.QAction(total)
        self.action_stop.setObjectName(_fromUtf8("action_stop"))
        self.action_21 = QtGui.QAction(total)
        self.action_21.setObjectName(_fromUtf8("action_21"))
        self.action_about = QtGui.QAction(total)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action = QtGui.QAction(total)
        self.action.setObjectName(_fromUtf8("action"))
        self.menuMain.addAction(self.action_load_file)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.action)
        self.menuMain.addAction(self.action_save_process)
        self.menuMain.addAction(self.action_load_process)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.action_about)
        self.menuRun.addAction(self.action_run_direct)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.action_1_IPS)
        self.menuRun.addAction(self.action_2_IPS)
        self.menuRun.addAction(self.action_4_IPS)
        self.menuRun.addAction(self.action_8_IPS)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.action_step)
        self.menuRun.addAction(self.action_pause)
        self.menuRun.addAction(self.action_stop)
        self.menuTool.addAction(self.action_hex2dex)
        self.menuTool.addAction(self.action_dec2hex)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.action_read_memory)
        self.menuTool.addAction(self.action_write_memory)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.action_21)
        self.menuView.addAction(self.action_total)
        self.menuView.addAction(self.action_pipeline)
        self.menuView.addAction(self.action_instruction)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuTool.menuAction())

        self.retranslateUi(total)
        QtCore.QMetaObject.connectSlotsByName(total)

    def retranslateUi(self, total):
        total.setWindowTitle(_translate("total", "total", None))
        self.label_write_back.setText(_translate("total", "WRITE BACK", None))
        self.text_D_icode_5.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">icode</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x0</p></body></html>", None))
        self.text_D_icode_4.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">valE</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x00000000</p></body></html>", None))
        self.text_D_icode_3.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">icode</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0xA</p></body></html>", None))
        self.text_D_icode_2.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">icode</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0xA</p></body></html>", None))
        self.text_D_icode_6.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">icode</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0xA</p></body></html>", None))
        self.label_memory.setText(_translate("total", "MEMORY", None))
        self.label_20.setText(_translate("total", "TextLabel", None))
        self.label_execute.setText(_translate("total", "EXECUTE", None))
        self.label_22.setText(_translate("total", "TextLabel", None))
        self.label_decode.setText(_translate("total", "DECODE", None))
        self.text_D_icode.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">icode</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x0</p></body></html>", None))
        self.text_D_ifun.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ifun</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x0</p></body></html>", None))
        self.textBrowser_6.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rA</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0xF</p></body></html>", None))
        self.textBrowser_5.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rB</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0xF</p></body></html>", None))
        self.textBrowser_4.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">valC</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x00000000</p></body></html>", None))
        self.textBrowser_3.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">valP</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x00000000</p></body></html>", None))
        self.label_fetch.setText(_translate("total", "FETCH", None))
        self.text_F_predPC.setHtml(_translate("total", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">predPC</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0x000</p></body></html>", None))
        self.groupBox.setTitle(_translate("total", "寄存器们", None))
        item = self.table_register.horizontalHeaderItem(0)
        item.setText(_translate("total", "REGISTER", None))
        item = self.table_register.horizontalHeaderItem(1)
        item.setText(_translate("total", "VALUE", None))
        self.groupBox_2.setTitle(_translate("total", "内存", None))
        self.button_continue.setText(_translate("total", "继续运行", None))
        self.button_pause.setText(_translate("total", "暂停一下", None))
        self.button_stop.setText(_translate("total", "停止程序", None))
        self.button_step.setText(_translate("total", "单步执行", None))
        self.button_reset.setText(_translate("total", "重置", None))
        self.menuMain.setTitle(_translate("total", "菜单", None))
        self.menuRun.setTitle(_translate("total", "运行", None))
        self.menuTool.setTitle(_translate("total", "小工具", None))
        self.menuView.setTitle(_translate("total", "视图", None))
        self.actionSo.setText(_translate("total", "so", None))
        self.action_run_direct.setText(_translate("total", "直接运行", None))
        self.action1_IPS.setText(_translate("total", "1-IPS", None))
        self.action2_IPS.setText(_translate("total", "2-IPS", None))
        self.action3.setText(_translate("total", "3", None))
        self.action_1_IPS.setText(_translate("total", "1-IPS", None))
        self.action_2_IPS.setText(_translate("total", "2-IPS", None))
        self.action_4_IPS.setText(_translate("total", "4-IPS", None))
        self.action_8_IPS.setText(_translate("total", "8-IPS", None))
        self.action_step.setText(_translate("total", "单步执行", None))
        self.action_hex2dex.setText(_translate("total", "hex2dec", None))
        self.action_dec2hex.setText(_translate("total", "dec2hex", None))
        self.action_7.setText(_translate("total", "保存进度", None))
        self.action_load_file.setText(_translate("total", "载入汇编文件", None))
        self.action_save_process.setText(_translate("total", "保存进度", None))
        self.action_load_process.setText(_translate("total", "载入进度", None))
        self.actionAbout.setText(_translate("total", "about", None))
        self.action_14.setText(_translate("total", "修改内存值", None))
        self.action_read_memory.setText(_translate("total", "查看内存", None))
        self.action_write_memory.setText(_translate("total", "修改内存", None))
        self.action_total.setText(_translate("total", "1-total", None))
        self.action_pipeline.setText(_translate("total", "2-pipeline", None))
        self.action_instruction.setText(_translate("total", "3-too simple", None))
        self.action_pause.setText(_translate("total", "暂停", None))
        self.action_stop.setText(_translate("total", "停止", None))
        self.action_21.setText(_translate("total", "y86编辑器", None))
        self.action_about.setText(_translate("total", "about", None))
        self.action.setText(_translate("total", "新增进度", None))

