# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total.ui'
#
# Created: Fri Jun 05 20:50:26 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_total(object):
    def setupUi(self, total):
        total.setObjectName(_fromUtf8("total"))
        total.setEnabled(True)
        total.resize(1000, 600)
        self.centralWidget = QtGui.QWidget(total)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(620, 0, 381, 201))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(620, 210, 381, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 230, 171, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.table_register = QtGui.QTableWidget(self.groupBox)
        self.table_register.setGeometry(QtCore.QRect(10, 20, 144, 227))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_register.sizePolicy().hasHeightForWidth())
        self.table_register.setSizePolicy(sizePolicy)
        self.table_register.setShowGrid(True)
        self.table_register.setWordWrap(True)
        self.table_register.setCornerButtonEnabled(True)
        self.table_register.setObjectName(_fromUtf8("table_register"))
        self.table_register.setColumnCount(2)
        self.table_register.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_register.setHorizontalHeaderItem(1, item)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 10, 201, 191))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(60, 210, 241, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 230, 160, 251))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.button_continue = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_continue.sizePolicy().hasHeightForWidth())
        self.button_continue.setSizePolicy(sizePolicy)
        self.button_continue.setObjectName(_fromUtf8("button_continue"))
        self.verticalLayout_3.addWidget(self.button_continue)
        self.button_pause = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setObjectName(_fromUtf8("button_pause"))
        self.verticalLayout_3.addWidget(self.button_pause)
        self.button_stop = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop.sizePolicy().hasHeightForWidth())
        self.button_stop.setSizePolicy(sizePolicy)
        self.button_stop.setObjectName(_fromUtf8("button_stop"))
        self.verticalLayout_3.addWidget(self.button_stop)
        self.button_step = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_step.sizePolicy().hasHeightForWidth())
        self.button_step.setSizePolicy(sizePolicy)
        self.button_step.setObjectName(_fromUtf8("button_step"))
        self.verticalLayout_3.addWidget(self.button_step)
        self.button_reset = QtGui.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setObjectName(_fromUtf8("button_reset"))
        self.verticalLayout_3.addWidget(self.button_reset)
        total.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(total)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMain = QtGui.QMenu(self.menuBar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuTool = QtGui.QMenu(self.menuBar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        total.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(total)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        total.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(total)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        total.setStatusBar(self.statusBar)
        self.actionSo = QtGui.QAction(total)
        self.actionSo.setObjectName(_fromUtf8("actionSo"))
        self.action_run_direct = QtGui.QAction(total)
        self.action_run_direct.setObjectName(_fromUtf8("action_run_direct"))
        self.action1_IPS = QtGui.QAction(total)
        self.action1_IPS.setObjectName(_fromUtf8("action1_IPS"))
        self.action2_IPS = QtGui.QAction(total)
        self.action2_IPS.setObjectName(_fromUtf8("action2_IPS"))
        self.action3 = QtGui.QAction(total)
        self.action3.setObjectName(_fromUtf8("action3"))
        self.action_1_IPS = QtGui.QAction(total)
        self.action_1_IPS.setObjectName(_fromUtf8("action_1_IPS"))
        self.action_2_IPS = QtGui.QAction(total)
        self.action_2_IPS.setObjectName(_fromUtf8("action_2_IPS"))
        self.action_4_IPS = QtGui.QAction(total)
        self.action_4_IPS.setObjectName(_fromUtf8("action_4_IPS"))
        self.action_8_IPS = QtGui.QAction(total)
        self.action_8_IPS.setObjectName(_fromUtf8("action_8_IPS"))
        self.action_step = QtGui.QAction(total)
        self.action_step.setObjectName(_fromUtf8("action_step"))
        self.action_hex2dex = QtGui.QAction(total)
        self.action_hex2dex.setObjectName(_fromUtf8("action_hex2dex"))
        self.action_dec2hex = QtGui.QAction(total)
        self.action_dec2hex.setObjectName(_fromUtf8("action_dec2hex"))
        self.action_7 = QtGui.QAction(total)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_load_file = QtGui.QAction(total)
        self.action_load_file.setVisible(True)
        self.action_load_file.setObjectName(_fromUtf8("action_load_file"))
        self.action_save_process = QtGui.QAction(total)
        self.action_save_process.setObjectName(_fromUtf8("action_save_process"))
        self.action_load_process = QtGui.QAction(total)
        self.action_load_process.setObjectName(_fromUtf8("action_load_process"))
        self.actionAbout = QtGui.QAction(total)
        self.actionAbout.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        self.actionAbout.setFont(font)
        self.actionAbout.setIconVisibleInMenu(False)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_14 = QtGui.QAction(total)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_read_memory = QtGui.QAction(total)
        self.action_read_memory.setObjectName(_fromUtf8("action_read_memory"))
        self.action_write_memory = QtGui.QAction(total)
        self.action_write_memory.setObjectName(_fromUtf8("action_write_memory"))
        self.action_total = QtGui.QAction(total)
        self.action_total.setObjectName(_fromUtf8("action_total"))
        self.action_pipeline = QtGui.QAction(total)
        self.action_pipeline.setObjectName(_fromUtf8("action_pipeline"))
        self.action_instruction = QtGui.QAction(total)
        self.action_instruction.setObjectName(_fromUtf8("action_instruction"))
        self.action_pause = QtGui.QAction(total)
        self.action_pause.setObjectName(_fromUtf8("action_pause"))
        self.action_stop = QtGui.QAction(total)
        self.action_stop.setObjectName(_fromUtf8("action_stop"))
        self.action_21 = QtGui.QAction(total)
        self.action_21.setObjectName(_fromUtf8("action_21"))
        self.action_about = QtGui.QAction(total)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action = QtGui.QAction(total)
        self.action.setObjectName(_fromUtf8("action"))
        self.menuMain.addAction(self.action_load_file)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.action)
        self.menuMain.addAction(self.action_save_process)
        self.menuMain.addAction(self.action_load_process)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.action_about)
        self.menuRun.addAction(self.action_run_direct)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.action_1_IPS)
        self.menuRun.addAction(self.action_2_IPS)
        self.menuRun.addAction(self.action_4_IPS)
        self.menuRun.addAction(self.action_8_IPS)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.action_step)
        self.menuRun.addAction(self.action_pause)
        self.menuRun.addAction(self.action_stop)
        self.menuTool.addAction(self.action_hex2dex)
        self.menuTool.addAction(self.action_dec2hex)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.action_read_memory)
        self.menuTool.addAction(self.action_write_memory)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.action_21)
        self.menuView.addAction(self.action_total)
        self.menuView.addAction(self.action_pipeline)
        self.menuView.addAction(self.action_instruction)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuTool.menuAction())

        self.retranslateUi(total)
        QtCore.QMetaObject.connectSlotsByName(total)

    def retranslateUi(self, total):
        total.setWindowTitle(_translate("total", "total", None))
        self.groupBox.setTitle(_translate("total", "寄存器们", None))
        item = self.table_register.horizontalHeaderItem(0)
        item.setText(_translate("total", "REGISTER", None))
        item = self.table_register.horizontalHeaderItem(1)
        item.setText(_translate("total", "VALUE", None))
        self.groupBox_2.setTitle(_translate("total", "内存", None))
        self.button_continue.setText(_translate("total", "继续运行", None))
        self.button_pause.setText(_translate("total", "暂停一下", None))
        self.button_stop.setText(_translate("total", "停止程序", None))
        self.button_step.setText(_translate("total", "单步执行", None))
        self.button_reset.setText(_translate("total", "重置", None))
        self.menuMain.setTitle(_translate("total", "菜单", None))
        self.menuRun.setTitle(_translate("total", "运行", None))
        self.menuTool.setTitle(_translate("total", "小工具", None))
        self.menuView.setTitle(_translate("total", "视图", None))
        self.actionSo.setText(_translate("total", "so", None))
        self.action_run_direct.setText(_translate("total", "直接运行", None))
        self.action1_IPS.setText(_translate("total", "1-IPS", None))
        self.action2_IPS.setText(_translate("total", "2-IPS", None))
        self.action3.setText(_translate("total", "3", None))
        self.action_1_IPS.setText(_translate("total", "1-IPS", None))
        self.action_2_IPS.setText(_translate("total", "2-IPS", None))
        self.action_4_IPS.setText(_translate("total", "4-IPS", None))
        self.action_8_IPS.setText(_translate("total", "8-IPS", None))
        self.action_step.setText(_translate("total", "单步执行", None))
        self.action_hex2dex.setText(_translate("total", "hex2dec", None))
        self.action_dec2hex.setText(_translate("total", "dec2hex", None))
        self.action_7.setText(_translate("total", "保存进度", None))
        self.action_load_file.setText(_translate("total", "载入汇编文件", None))
        self.action_save_process.setText(_translate("total", "保存进度", None))
        self.action_load_process.setText(_translate("total", "载入进度", None))
        self.actionAbout.setText(_translate("total", "about", None))
        self.action_14.setText(_translate("total", "修改内存值", None))
        self.action_read_memory.setText(_translate("total", "查看内存", None))
        self.action_write_memory.setText(_translate("total", "修改内存", None))
        self.action_total.setText(_translate("total", "1-total", None))
        self.action_pipeline.setText(_translate("total", "2-pipeline", None))
        self.action_instruction.setText(_translate("total", "3-too simple", None))
        self.action_pause.setText(_translate("total", "暂停", None))
        self.action_stop.setText(_translate("total", "停止", None))
        self.action_21.setText(_translate("total", "y86编辑器", None))
        self.action_about.setText(_translate("total", "about", None))
        self.action.setText(_translate("total", "新增进度", None))

